import { Patient } from './@types/Patient';

export const fakePatients: Patient[] = [
  {
    id: '1111111111',
    name: 'João da Silva Oliveira',
    email: 'joaodasilvaoliveira@gmail.com',
    phone: '44123456789',
    birthDate: new Date('2000-01-01'),
    image: 'https://github.com/rafarod21.png',
    address: {
      cep: '99999000',
      street: 'Rua Carlos de Almeida Thiago',
      number: 99,
      district: 'Vila Nova',
      complement: 'Ap 518',
      city: 'Curitiba',
      uf: 'PR',
    },
  },
  {
    id: '2222222222',
    name: 'João da Silva Oliveira',
    email: 'joaodasilvaoliveira@gmail.com',
    phone: '44123456789',
    birthDate: new Date('2000-01-01'),
    image: 'https://github.com/rafarod21.png',
    address: {
      cep: '99999000',
      street: 'Rua Carlos de Almeida Thiago',
      number: 99,
      district: 'Vila Nova',
      complement: 'Ap 518',
      city: 'Curitiba',
      uf: 'PR',
    },
  },
  {
    id: '3333333333',
    name: 'João da Silva Oliveira',
    email: 'joaodasilvaoliveira@gmail.com',
    phone: '44123456789',
    birthDate: new Date('2000-01-01'),
    image: 'https://github.com/rafarod21.png',
    address: {
      cep: '99999000',
      street: 'Rua Carlos de Almeida Thiago',
      number: 99,
      district: 'Vila Nova',
      complement: 'Ap 518',
      city: 'Curitiba',
      uf: 'PR',
    },
  },
  {
    id: '4444444444',
    name: 'João da Silva Oliveira',
    email: 'joaodasilvaoliveira@gmail.com',
    phone: '44123456789',
    birthDate: new Date('2000-01-01'),
    image: 'https://github.com/rafarod21.png',
    address: {
      cep: '99999000',
      street: 'Rua Carlos de Almeida Thiago',
      number: 99,
      district: 'Vila Nova',
      complement: 'Ap 518',
      city: 'Curitiba',
      uf: 'PR',
    },
  },
  {
    id: '5555555555',
    name: 'João da Silva Oliveira',
    email: 'joaodasilvaoliveira@gmail.com',
    phone: '44123456789',
    birthDate: new Date('2000-01-01'),
    image: 'https://github.com/rafarod21.png',
    address: {
      cep: '99999000',
      street: 'Rua Carlos de Almeida Thiago',
      number: 99,
      district: 'Vila Nova',
      complement: 'Ap 518',
      city: 'Curitiba',
      uf: 'PR',
    },
  },
  {
    id: '6666666666',
    name: 'João da Silva Oliveira',
    email: 'joaodasilvaoliveira@gmail.com',
    phone: '44123456789',
    birthDate: new Date('2000-01-01'),
    image: 'https://github.com/rafarod21.png',
    address: {
      cep: '99999000',
      street: 'Rua Carlos de Almeida Thiago',
      number: 99,
      district: 'Vila Nova',
      complement: 'Ap 518',
      city: 'Curitiba',
      uf: 'PR',
    },
  },
];
